import type { Metadata } from 'next'
import { LegalPage, Section, SubSection, UL, WarningBox, InfoBox, AcknowledgmentBox } from '../components'

export const metadata: Metadata = {
  title: 'Disclaimer — TradVue',
  description: 'Important legal disclaimer: TradVue is not a financial advisor and does not provide investment advice. Read before using the platform.',
  alternates: {
    canonical: 'https://tradvue.com/legal/disclaimer',
  },
  robots: 'noindex, follow',
}

export default function DisclaimerPage() {
  return (
    <LegalPage title="Disclaimer" lastUpdated="March 16, 2026">

      <WarningBox>
        <strong>THIS DISCLAIMER IS PART OF TRADVUE'S LEGAL AGREEMENT WITH YOU. BY USING THE SERVICE, YOU
        ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREED TO THIS DISCLAIMER.</strong>
        <br /><br />
        See also:{' '}
        <a href="/legal/terms" style={{ color: '#ef4444' }}>Terms of Service</a>
        {' '} | {' '}
        <a href="/legal/privacy" style={{ color: '#ef4444' }}>Privacy Policy</a>
      </WarningBox>

      <Section id="not-advice" title="1. NOT FINANCIAL ADVICE">
        <WarningBox>
          THE TRADVUE PLATFORM, INCLUDING ALL FEATURES, CONTENT, ANALYTICS, DATA, TOOLS, AI COACH OUTPUTS,
          MARKET DATA, JOURNAL ANALYTICS, AND ANY OTHER INFORMATION PROVIDED THROUGH THE SERVICE, IS FOR
          INFORMATIONAL, JOURNALING, AND ANALYTICAL PURPOSES ONLY. NOTHING ON TRADVUE CONSTITUTES FINANCIAL
          ADVICE, INVESTMENT ADVICE, TRADING ADVICE, TAX ADVICE, LEGAL ADVICE, OR ANY OTHER TYPE OF REGULATED
          PROFESSIONAL ADVICE.
          <br /><br />
          NO CONTENT ON TRADVUE SHOULD BE CONSTRUED AS A RECOMMENDATION, SOLICITATION, OR OFFER TO BUY, SELL,
          HOLD, OR OTHERWISE TRANSACT IN ANY SECURITY, COMMODITY, CRYPTOCURRENCY, FUTURES CONTRACT, OPTIONS
          CONTRACT, OR OTHER FINANCIAL INSTRUMENT.
        </WarningBox>
        <p>
          <strong>1.1 Informational Purpose.</strong> TradVue is a journaling and analytics tool. Its purpose
          is to help you organize, review, and analyze your own historical trading data — not to guide future
          investment decisions.
        </p>
        <p>
          <strong>1.2 No Advisory Relationship.</strong> Your use of TradVue does not create a financial
          advisory, broker-dealer, or fiduciary relationship between you and TradVue or Apex Logics LLC.
        </p>
        <InfoBox>
          <strong>If you need financial, tax, or legal advice, consult with a licensed financial advisor,
          tax professional, attorney, broker, or investment professional.</strong>
        </InfoBox>
      </Section>

      <Section id="not-ria" title="2. Not a Registered Investment Adviser">
        <WarningBox>
          APEX LOGICS LLC (D/B/A TRADVUE) IS NOT REGISTERED AS AN INVESTMENT ADVISER WITH THE UNITED STATES
          SECURITIES AND EXCHANGE COMMISSION ("SEC") UNDER THE INVESTMENT ADVISERS ACT OF 1940, AS AMENDED
          (15 U.S.C. § 80B-1 ET SEQ.), NOR IS IT REGISTERED OR LICENSED AS AN INVESTMENT ADVISER UNDER ANY
          APPLICABLE STATE SECURITIES LAW.
        </WarningBox>
        <p>
          TradVue does not provide, and nothing on the TradVue platform should be construed as, "investment
          advice" as defined under the Investment Advisers Act of 1940. TradVue is not a "financial planner,"
          "financial consultant," "wealth manager," or any other type of regulated financial professional.
        </p>
      </Section>

      <Section id="not-broker" title="3. Not a Broker-Dealer">
        <WarningBox>
          APEX LOGICS LLC (D/B/A TRADVUE) IS NOT REGISTERED AS A BROKER-DEALER WITH THE SEC UNDER THE
          SECURITIES EXCHANGE ACT OF 1934, AS AMENDED (15 U.S.C. § 78A ET SEQ.), AND IS NOT A MEMBER OF THE
          FINANCIAL INDUSTRY REGULATORY AUTHORITY ("FINRA") OR THE SECURITIES INVESTOR PROTECTION CORPORATION
          ("SIPC").
        </WarningBox>
        <p>
          TradVue does not execute, route, or facilitate the purchase or sale of any securities or other
          financial instruments. TradVue does not hold customer funds or securities. Your brokerage relationship
          is solely with your registered broker-dealer.
        </p>
      </Section>

      <Section id="ai-coach" title="4. AI Coach Disclaimer">
        <WarningBox>
          THE AI COACH FEATURE IS AN AUTOMATED ANALYTICAL TOOL POWERED BY ARTIFICIAL INTELLIGENCE. IT IS NOT
          A FINANCIAL ADVISER, INVESTMENT ADVISER, OR TRADING SYSTEM. AI COACH IS NOT DESIGNED OR INTENDED
          TO PROVIDE, AND DOES NOT PROVIDE, PERSONALIZED INVESTMENT ADVICE OR RECOMMENDATIONS.
        </WarningBox>
        <p>
          <strong>4.1 AI Limitations.</strong> AI Coach outputs are generated by machine learning models
          (via OpenAI's API) that analyze your historical trade data. These outputs:
        </p>
        <UL items={[
          'May be inaccurate, incomplete, misleading, or factually incorrect;',
          'Are not personalized to your individual financial situation, investment objectives, risk tolerance, time horizon, or tax circumstances;',
          'Do not account for real-time market conditions, regulatory changes, or events occurring after the data analyzed;',
          'Reflect limitations and potential biases inherent in large language models and AI systems;',
          'Should not be treated as reliable predictions of future trading performance.',
        ]} />
        <p>
          <strong>4.2 Independent Verification Required.</strong> You should not rely on AI Coach output for
          any trading or investment decision without independent verification by a qualified financial
          professional and your own due diligence.
        </p>
        <p>
          <strong>4.3 No Substitute for Professional Advice.</strong> AI Coach is not a substitute for advice
          from a licensed investment adviser, broker-dealer, or other qualified financial professional who
          understands your complete financial situation.
        </p>
        <p>
          <strong>4.4 User Responsibility.</strong> All investment and trading decisions are solely your
          responsibility. TradVue accepts no responsibility for any losses or adverse outcomes resulting from
          reliance on AI Coach outputs.
        </p>
      </Section>

      <Section id="market-data" title="5. Market Data Disclaimer">
        <p>
          <strong>5.1 Third-Party Data.</strong> Market data, price quotes, financial news, and other market
          information displayed on TradVue are obtained from third-party providers (Alpaca Markets, Marketaux,
          Finnhub, and others). TradVue does not independently generate, verify, or warrant the accuracy of
          this data.
        </p>
        <p>
          <strong>5.2 Data May Be Delayed.</strong> Market data displayed on TradVue may be delayed by 15
          minutes or more. Delayed data is not suitable for real-time trading decisions.
        </p>
        <p>
          <strong>5.3 Potential Errors.</strong> Market data may contain errors, gaps, or inaccuracies. Prices
          displayed may not reflect actual executable prices.
        </p>
        <p>
          <strong>5.4 Not Suitable for Real-Time Trading.</strong> Do not rely on TradVue market data as the
          sole source for real-time trading decisions. Always verify pricing and data through your broker, the
          relevant exchange, or other official sources before executing any trade.
        </p>
        <p>
          <strong>5.5 No Warranty on Data.</strong> TRADVUE MAKES NO WARRANTY, EXPRESS OR IMPLIED, REGARDING
          THE ACCURACY, COMPLETENESS, OR TIMELINESS OF ANY MARKET DATA.
        </p>
      </Section>

      <Section id="broker-sync" title="6. Broker Sync Disclaimer">
        <p>
          <strong>6.1 Third-Party Accuracy.</strong> When you import trade data via CSV or, where available,
          automated broker synchronization, the data TradVue displays reflects what was imported from
          third-party sources. TradVue does not independently verify the accuracy of imported or synchronized
          data.
        </p>
        <p>
          <strong>6.2 Potential Discrepancies.</strong> Data imported from brokers may:
        </p>
        <UL items={[
          'Contain errors, omissions, or discrepancies compared to your actual trade executions;',
          'Reflect delayed or incomplete information due to API limitations;',
          'Differ from official broker statements.',
        ]} />
        <p>
          <strong>6.3 Official Statements Control.</strong> Your official broker statements, confirmations,
          and account records are the authoritative source for your trade and account data. In any discrepancy
          between TradVue and your broker, your broker's records control.
        </p>
        <p>
          <strong>6.4 No Liability for Broker Errors.</strong> TradVue is not responsible for errors,
          failures, or inaccuracies originating from your broker, from third-party data aggregators, or from
          the CSV data you import.
        </p>
      </Section>

      <Section id="warranties" title="7. No Warranties">
        <WarningBox>
          THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE FULLEST EXTENT PERMITTED BY
          APPLICABLE LAW, TRADVUE AND APEX LOGICS LLC EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER
          EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO:
          <br /><br />
          (A) WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT;
          <br /><br />
          (B) WARRANTIES THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE;
          <br /><br />
          (C) WARRANTIES AS TO THE ACCURACY, RELIABILITY, COMPLETENESS, OR CURRENCY OF ANY CONTENT, DATA, OR
          INFORMATION PROVIDED THROUGH THE SERVICE;
          <br /><br />
          (D) WARRANTIES THAT DEFECTS WILL BE CORRECTED.
        </WarningBox>
      </Section>

      <Section id="liability" title="8. Limitation of Liability">
        <WarningBox>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL APEX LOGICS LLC, TRADVUE, OR
          THEIR RESPECTIVE OFFICERS, DIRECTORS, MEMBERS, EMPLOYEES, AGENTS, LICENSORS, OR SERVICE PROVIDERS
          BE LIABLE FOR:
          <br /><br />
          (A) ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES;
          <br /><br />
          (B) ANY TRADING LOSSES, INVESTMENT LOSSES, OR FINANCIAL LOSSES OF ANY KIND;
          <br /><br />
          (C) ANY LOSS OF DATA, REVENUE, PROFITS, GOODWILL, OR BUSINESS OPPORTUNITIES;
          <br /><br />
          ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE, OR YOUR RELIANCE
          ON ANY INFORMATION, ANALYTICS, AI COACH OUTPUT, OR MARKET DATA PROVIDED THROUGH THE SERVICE.
          <br /><br />
          TRADVUE'S TOTAL CUMULATIVE LIABILITY TO YOU SHALL NOT EXCEED THE TOTAL SUBSCRIPTION FEES ACTUALLY
          PAID BY YOU TO TRADVUE DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE
          TO THE CLAIM, OR $100.00, WHICHEVER IS GREATER.
        </WarningBox>
      </Section>

      <Section id="risk" title="9. Risk Disclosure and Assumption of Risk">
        <WarningBox>
          TRADING IN SECURITIES, EQUITIES, OPTIONS, FUTURES, FOREIGN EXCHANGE, CRYPTOCURRENCIES, AND OTHER
          FINANCIAL INSTRUMENTS INVOLVES SUBSTANTIAL RISK OF LOSS. YOU MAY LOSE ALL OR MORE THAN YOUR INITIAL
          INVESTMENT. PAST PERFORMANCE IS NOT INDICATIVE OF FUTURE RESULTS. THERE IS NO GUARANTEE THAT ANY
          TRADING STRATEGY, SYSTEM, OR TOOL — INCLUDING TRADVUE — WILL RESULT IN PROFITS OR PREVENT LOSSES.
          <br /><br />
          BY USING TRADVUE, YOU EXPRESSLY ACKNOWLEDGE AND ACCEPT THAT:
          <ul style={{ marginTop: '10px', paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <li>(A) TRADING INVOLVES SUBSTANTIAL RISK OF LOSS, UP TO AND INCLUDING THE TOTAL LOSS OF ALL INVESTED CAPITAL;</li>
            <li>(B) YOU ARE SOLELY RESPONSIBLE FOR ALL TRADING AND INVESTMENT DECISIONS YOU MAKE;</li>
            <li>(C) TRADVUE'S ANALYTICS AND AI COACH FEATURES ARE TOOLS TO REVIEW YOUR PAST ACTIVITY, NOT PREDICTIONS OR GUARANTEES OF FUTURE PERFORMANCE;</li>
            <li>(D) YOU HAVE SUFFICIENT KNOWLEDGE, EXPERIENCE, AND FINANCIAL RESOURCES TO BEAR THE RISKS OF YOUR TRADING ACTIVITY;</li>
            <li>(E) YOU WILL NOT HOLD TRADVUE OR APEX LOGICS LLC LIABLE FOR ANY TRADING LOSSES, REGARDLESS OF WHETHER YOU REVIEWED TRADVUE DATA BEFORE MAKING A TRADING DECISION.</li>
          </ul>
        </WarningBox>
      </Section>

      <Section id="tax" title="10. Tax Disclaimer">
        <p>
          <strong>TradVue does not provide tax advice.</strong> The performance data, P&amp;L calculations,
          and analytics displayed in TradVue are for journaling and self-analysis purposes only and are{' '}
          <strong>not</strong> intended for use in tax reporting. TradVue's calculations may not match the
          calculations used by your broker for tax purposes (e.g., wash sale rules, cost basis methods,
          short-term vs. long-term treatment).
        </p>
        <p>
          You are solely responsible for accurately reporting your trading income, gains, and losses to the
          applicable tax authorities.
        </p>
        <WarningBox>
          <strong>Consult a qualified tax professional or CPA before using TradVue data for any tax filing purpose.</strong>
        </WarningBox>
      </Section>

      <Section id="hypothetical" title="11. Hypothetical and Historical Performance">
        <p>
          <strong>11.1 Past Performance.</strong> Any historical trading data or performance metrics displayed
          in TradVue reflect your past trading activity only. They do not constitute a representation or
          guarantee of future trading results.
        </p>
        <p>
          <strong>11.2 Hypothetical Results.</strong> Any backtesting, hypothetical analysis, or "what-if"
          scenarios available on TradVue are simulated and subject to known and unknown limitations:
        </p>
        <UL items={[
          'Hypothetical performance does not represent actual trading results;',
          'Hypothetical results may not reflect the impact of actual market conditions, liquidity, slippage, commissions, or other transaction costs;',
          'The ability to replicate hypothetical results is not guaranteed.',
        ]} />
        <p>
          <strong>11.3 No Guarantee.</strong> TradVue makes no representation or warranty that any trading
          strategy, playbook, or approach reflected in your TradVue data will result in profits in the future.
        </p>
      </Section>

      <Section id="third-party" title="12. Third-Party Content and Links">
        <p>
          <strong>12.1 Third-Party Information.</strong> TradVue may display content, data, news, analysis,
          or links provided by third parties (including Market Data Providers). TradVue does not endorse,
          verify, or assume responsibility for the accuracy, completeness, or legality of any third-party content.
        </p>
        <p>
          <strong>12.2 Third-Party Links.</strong> The Service may contain links to third-party websites or
          services. These links are provided for convenience only. TradVue has no control over the content of
          linked sites and is not responsible for their privacy practices or content. Your use of third-party
          websites is at your own risk and subject to the terms and policies of those sites.
        </p>
        <p>
          <strong>12.3 No Endorsement.</strong> Reference to any third-party product, service, provider, or
          website does not constitute an endorsement by TradVue.
        </p>
      </Section>

      <Section id="compliance" title="13. Regulatory and Legal Compliance">
        <p>
          Users of TradVue are solely responsible for ensuring that their trading activities comply with all
          applicable laws and regulations in their jurisdiction, including but not limited to:
        </p>
        <UL items={[
          'Securities laws (Securities Act of 1933, Securities Exchange Act of 1934, and state blue sky laws)',
          'Commodity trading regulations (Commodity Exchange Act, CFTC regulations)',
          'Anti-fraud and market manipulation prohibitions',
          'Insider trading laws',
          'Tax reporting obligations',
          'Export control laws',
        ]} />
        <p>
          TradVue does not monitor users for regulatory compliance and does not provide legal or compliance advice.
        </p>
      </Section>

      <Section id="contact" title="14. Contact">
        <p>For questions regarding this Disclaimer:</p>
        <InfoBox>
          <strong>Apex Logics LLC d/b/a TradVue</strong><br />
          1935 Commerce Lane, Suite 9<br />
          Jupiter, FL 33458<br /><br />
          Legal:{' '}
          <a href="mailto:legal@tradvue.com" style={{ color: '#4a9eff' }}>legal@tradvue.com</a><br />
          Website: <a href="https://tradvue.com" style={{ color: '#4a9eff' }}>https://tradvue.com</a>
        </InfoBox>
        <p style={{ marginTop: '8px', fontSize: '13px', color: 'var(--text-2)' }}>
          TradVue is a product of Apex Logics LLC.<br />
          Apex Logics LLC, FL Doc# L23000460971, DBA Reg# G26000036763.<br />
          Effective Date: March 16, 2026
        </p>
      </Section>

      <Section id="full-agreement" title="15. Full Agreement">
        <p>
          This Disclaimer, combined with our{' '}
          <a href="/legal/terms" style={{ color: '#4a9eff' }}>Terms of Service</a>,{' '}
          <a href="/legal/privacy" style={{ color: '#4a9eff' }}>Privacy Policy</a>,{' '}
          <a href="/legal/cookies" style={{ color: '#4a9eff' }}>Cookie Policy</a>, and{' '}
          <a href="/legal/aup" style={{ color: '#4a9eff' }}>Acceptable Use Policy</a>,
          constitutes the complete agreement between you and TradVue regarding the use of the platform.
        </p>
      </Section>

      <AcknowledgmentBox>
        By using TradVue, you certify that you have read this entire Disclaimer, understand the risks of
        trading and investing, acknowledge that TradVue provides no financial advice, and accept all
        limitations and disclaimers outlined above. <strong>Use at Your Own Risk ⚠️</strong>
      </AcknowledgmentBox>

    </LegalPage>
  )
}
